version: '2'
services:
  nest-db:
    image: postgres:16.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    volumes:
      - ./pg_data:/var/lib/postgresql/data
